[phases.setup]
nixPkgs = ["jdk21"]

[phases.build]
cmds = ["./gradlew build -x test"]

[start]
cmd = "java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar build/libs/CreativeLearningCenter-0.0.1-SNAPSHOT.jar"